version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-magical-bedtime-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    # environment:
    #   - REACT_APP_API_URL=http://localhost:5000/api
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-magical-bedtime-backend
    ports:
      - "5500:5500"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # depends_on:
    #   - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CORS_ORIGIN=http://localhost:5173  # Allow frontend to connect
    stdin_open: true
    tty: true
      # - MONGODB_URI=mongodb://mongodb:27017/mymagicalbedtime
      # - JWT_SECRET=your_jwt_secret_key_here
      # - JWT_EXPIRES_IN=15m
      # - REFRESH_TOKEN_SECRET=your_refresh_token_secret_here
      # - REFRESH_TOKEN_EXPIRES_IN=7d

